Milestone4
Tahirbhalli/react-calculator pull request #5
Opened 2020-08-19 14:46 UTC by Tahirbhalli

In this Milestone I add:

Logic foder and work on the logics of the calculator
npm install
npm start
note: I was not able to submit my project milestones So in Heroku I deployed the whole project,

2020-08-20 19:49 UTC, Forison requested changes
## Status:: Changes Required❌

# 🙋‍♂️ @Tahirbhalli,

#### You have a great job so far, but your project is very different from what the requirement ought to yield after following them🤗.

* [x] Kindly check milestone 3 for UI designs [check this out](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896082/).

* [x] The following basic functionalities are missing ie ```%, AC, -/+```.

* [x] Disabling linters will let you miss out on some important practices that you should know.

**[OPTIONAL]**

* [ ] It is better to have semantic Branch names, it would have been better to name this branch milestone 5.

## That is it kindly check on these requirements and submit a re-review🤗.

#### Happy coding👨‍💻

Addo Forison

2020-08-20 19:58 UTC, suretrust requested changes
Hi @Tahirbhalli, 👋 

### Great job thus far! 🙌 Please see my comments. 👇 

- [ ] All the `eslint` laws that you disabled are needed, let's remove all and follow best and modern practices.

**KIndly submit another CRR once these issues have been solved.** _Happy coding!_ 🎉

2020-08-20 19:58 UTC, suretrust commented on src/component/Button.js
> +/* eslint-disable react/button-has-type */
I see no reason why you should disable these rules, you just need to understand them and write your code accordingly. 

- [ ] react/prop-types => If the `propType` does not have `isRequired`, ensure you add `defaultProps` value.

- [ ] react/destructuring-assignment => destructure where applicable, that's simply es6, which is a requirement for this project.

- [ ] react/button-has-type => add `type` attribute, example: `type="submit"`.

Read more about `PropTypes` [here](https://reactjs.org/docs/typechecking-with-proptypes.html).

2020-08-20 19:58 UTC, suretrust commented on src/component/Button.js
> +      <button className={'double ' + `${props.color}`} onClick={() => handleclick(props.name)}>{props.name}</button>
- [ ] no-useless-concat => you could just use es6 entirely. 
```suggestion
      <button className={`double ${props.color}`} onClick={() => handleclick(props.name)}>{props.name}</button>
```

2020-08-20 19:58 UTC, suretrust commented on src/component/Button.js
> +Button.prototype = {
```suggestion
Button.propTypes = {
```

2020-08-20 19:58 UTC, suretrust commented on src/component/Button.js
> +};
```suggestion
Button.defaultProps = {
  color: 'orange',
  wide: false,
};
```

2020-08-20 19:58 UTC, suretrust commented on src/component/ButtonPanel.js
> +/* eslint-disable react/prop-types */
Remove the rule disable and add propTypes checking.
```suggestion
```

2020-08-20 19:58 UTC, suretrust commented on src/component/Display.js
> +/* eslint-disable react/destructuring-assignment */
```suggestion
```

2020-08-20 19:58 UTC, suretrust commented on src/component/Display.js
> +};
```suggestion
Display.propTypes = {
  result: PropTypes.string,
};
```

2020-08-20 19:58 UTC, suretrust commented on src/logic/operate.js
> +      return First % Second;
`%` should be treated as perentage, `59% === 59/100 === 0.59`.

2020-08-20 19:58 UTC, suretrust commented on src/logic/operate.js
> +      }
Let's handle this better, it should give some explanatory error, like `Can't divide by 0`, `undefined` is kind of vague.

2020-08-21 13:00 UTC, shloch approved these changes
## Hello @Tahirbhalli 
![accomplished](https://user-images.githubusercontent.com/40712459/90893249-8f8a9b00-e3b6-11ea-8cb9-acc6d045d0bc.jpg)

Great job with bringing the modifications

Keep up with the good work
Happy coding

2020-08-21 13:34 UTC, shloch requested changes
I reviewed for Milestone 4 above, then I claimed same project for Milestone 5....so this is a continuation

## Milestone 5 review

![calc](https://user-images.githubusercontent.com/40712459/90896266-3ec97100-e3bb-11ea-82cb-a4772b9eb6b3.gif)

Works very well, 
- except for division by zero
- on milestone 2, the default display on `Display` component, needed to have `0` on it, your calculator starts with a blank screen, debug this too

### [optional changes]

- since there's enough space on the buttons, can you increase the size of the button text ?? (for more visibility) 
- Can you center the whole calculator on screen? (for symmetry )

Please debug these little things, and file for last review hopefully

Happy coding

2020-08-21 13:34 UTC, shloch commented on src/logic/operate.js
> +      }
i see the code for managing this error, but it's not working on the design, debug this :)

2020-08-21 13:34 UTC, shloch commented on src/component/Display.js
> +};
make this `ZERO` appear on startup screen

2020-08-21 13:34 UTC, shloch commented on src/App.css
You can center the calculator
```
margin: auto;
```

2020-08-24 12:42 UTC, fatymahmed approved these changes
## Hi @Tahirbhalli    
### Good job making the requested changes🎉🎉
## Status: Approved ✔️
_For future projects, use a different PR for each milestone_

2020-08-24 14:51 UTC, merged